# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31feb170c9fd22ca743129891f62aeac5f3b05a7f9c1e55460b64055e4c5e3beb77d00933acb9970e801406fdebc05740830030e86f0af1bd12999c33629b817

test:
  secret_key_base: 6a82c5563dccc312ff5787103aa8f61059f18076a3174903a06279cd0f99950a5212c862e226cfe49d25e65fc0c367afefb0e83506f9ee86ee4ad6b644dc636f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
